name: Merge upstream changes

on:
  schedule:
    - cron: "0 * * * *" # Run the job every hour
  push:
    branches:
      - "*"
    paths:
      - .github/workflows/sync.yml

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge upstream changes (main)
        run: |
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
